### ISSUE TITLE
Missing _ in to_dict() in Element

### ISSUE THREAD

**Issue by HRD007** [geeknam/messengerbot#11]
Hi,

Thank you for your great work here.

I just discovered the underscores before title and subtitle are missing in to_dist() in your Element class. I.e. I changed:

```
def to_dict(self):
    serialised = {
        'title': self.title,
        'item_url': self.item_url,
        'image_url': self.image_url,
        'subtitle': self.subtitle
    }
```

to this with underscores
    def to_dict(self):
        serialised = {
            'title': self._title,
            'item_url': self.item_url,
            'image_url': self.image_url,
            'subtitle': self._subtitle
        }

Br, Henrik

PS. Not sure if this the right way to post it, as I am completely newbie here...

**Comment by geeknam** [comment]
There is a subtitle property that adds validation on top
