### ISSUE TITLE
I need some help setting-up webhooks via facebook-api/messenger platform in python

### ISSUE THREAD

**Issue by kirbyfern** [geeknam/messengerbot#22]
Using ngrok as a secure server for setting up webhooks , I am unable to continue the process : 

<img width="362" alt="screen shot 2017-02-20 at 8 35 12 pm" src="https://cloud.githubusercontent.com/assets/20747057/23150958/4aa484dc-f7ac-11e6-9f4f-dfd9d5fb360d.png">

The error above is the part wherein setting back Callback-URL
I run the command to use port 8080
```
./ngrok http 8080
```

**Comment by Elicherla01** [comment]
This usually happens if your Verify Token was not validated.

**Comment by kirbyfern** [comment]
Its been awhile however , what are the solution to this issue regarding Tokens. How do I make sure that the Token would assume a correct validation from Facebook

**Comment by Elicherla01** [comment]
In the code, please specify some value for Verify Token. This could be any random value. When you are connecting to facebook, you should use same value.
